feature/#118
VB-CORE/hatayi_yasat pull request #119
Opened 2023-11-03 05:48 UTC by BerkSartik

2 farklı görüntü olarak düşündüm. Gelen feedbacklere göre kodu güncelleyeceğim

1. Görüntü
![image](https://github.com/VB-CORE/life_client/assets/48359825/e0e06d26-3284-4fee-8bc7-2e2531635949)

2. Görüntü
![image](https://github.com/VB-CORE/life_client/assets/48359825/2c620cba-617e-48c4-b6ef-f6f57ab0c9cf)

2023-11-03 07:50 UTC, BerkSartik commented
Son hali bu şekilde güncellendi.
![image](https://github.com/VB-CORE/life_client/assets/48359825/b65e8c5d-0b35-4259-991a-a875d4342044)

2023-11-05 19:16 UTC, MehmetKaranlik requested changes

2023-11-05 19:16 UTC, MehmetKaranlik commented on lib/features/settings_module/settings/subview/app_rating_widget.dart
> +      initialRating: 5,
bu 5 leri const alsak daha iyi olur

2023-11-05 19:16 UTC, MehmetKaranlik commented on lib/features/settings_module/settings/subview/app_rating_widget.dart
> +      onRatingUpdate: (value) {},
burası kullanılmıyor mu ?

2023-11-08 04:21 UTC, BerkSartik commented on lib/features/settings_module/settings/subview/app_rating_widget.dart
> +      onRatingUpdate: (value) {},
Hocam bu wdiget ListTile ile sarılı olduğu için yönlendirmeyi o yapıyor gerekli yere. Görsel olarak duruyor yani sadece

2023-11-09 01:09 UTC, VB10 commented
@BerkSartik buna bilrikte bakalım sonra merge alıcam

2023-11-09 01:12 UTC, merged