feature/#135
VB-CORE/hatayi_yasat pull request #145
Opened 2023-11-19 22:14 UTC by BerkSartik

![image](https://github.com/VB-CORE/life_client/assets/48359825/b9a4a784-b94d-408f-8271-9d0e144a3c00)

2023-11-20 22:49 UTC, VB10 requested changes
ekleme ve ss koyar misin

2023-11-20 22:49 UTC, VB10 commented on lib/product/widget/listtile/author_listtile_widget.dart
> +class _AuthorCircleAvatar extends StatelessWidget {
final

2023-11-20 22:49 UTC, VB10 commented on lib/product/widget/listtile/author_listtile_widget.dart
> +      radius: AppConstants.kFourteen.toDouble(),
bu tarz radiuslari constant dan degil circleradius enumu yapip oradan generic hale getirelim

2023-11-20 22:49 UTC, VB10 commented on lib/product/widget/listtile/author_listtile_widget.dart
> +class _AuthorText extends StatelessWidget {
final

2023-11-21 14:33 UTC, BerkSartik commented
> ekleme ve ss koyar misin

Hocam eklemeden kastınız nedir anlayamadım. SS koymuştum ancak daha anlaşılır ekliyim tekrar

Edit: Ekleme derken yorumları kast etmişsiniz geç anladım pardon :D

![image](https://github.com/VB-CORE/life_client/assets/48359825/34be9420-d933-4a07-8ea8-a1a37a6815fc)

2023-11-21 22:57 UTC, merged

2023-11-21 22:57 UTC, VB10 commented
lgtm