News Card V2
VB-CORE/hatayi_yasat pull request #146
Opened 2023-11-19 22:24 UTC by BerkSartik

** Widget isminde bulunan V2 daha sonra kaldırılacak.

![image](https://github.com/VB-CORE/life_client/assets/48359825/75c46574-52ae-4d35-af01-39af9083b636)![image](https://github.com/VB-CORE/life_client/assets/48359825/db150b38-55c4-4172-81bd-e1675f6b48ed)

2023-11-19 22:24 UTC, BerkSartik commented
Bizim "News" datalarımızda şuan author image ve name yok. UIKit'de görünen olması için ekledim(author widget) ancak daha sonra kaldırmamız gerekebilir.

2023-11-20 22:51 UTC, VB10 requested changes
ekleme

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +class NewsCardV2 extends StatelessWidget {
final ve v2 kaldiralim(yorumunu gordum farke temez kalksin)

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +class _NewsImage extends StatelessWidget {
final

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +    const dummyName = 'Baba Yaga Coffee';
dummy datalar remove bu sekilde dummy degil disaridan alirsin dummyi

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +class _NewsTitle extends StatelessWidget {
fuinal

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +  final String? title;
buraya gelen title null olamaz

2023-11-20 22:51 UTC, VB10 commented on lib/product/widget/card/news_card_v2.dart
> +      maxLines: 1,
default 1 olmali ama biz bunu iki yapalim

2023-11-21 22:58 UTC, VB10 commented
lgtm

2023-11-21 22:58 UTC, merged