Add button and jobs card design
VB-CORE/hatayi_yasat pull request #147
Opened 2023-11-19 23:08 UTC by MehmetKaranlik

@VB10  General button ve job kartı eklendi.
Yalnız bizim job modeliyle tasarımdaki kart uymuyor, resim yok mesela bizde iş ilanında olması mantıklı değil ordan bakarım bişeyler yaptım.

2023-11-20 01:04 UTC, BerkSartik commented
Buton için;
- Elevation kalkabilir.
- İçe dikey olarak boşluk eklenebilir çok yakın duruyor.

Job Card için;
- Aşağı açılır şekilde değil tıklanınca bottomsheet açılacak o yüzden o kaldırılabilir


Eğer farklı bir şey konuşulduysa  bilgim yok. UIKit'e göre yorumladım hocam

2023-11-20 22:45 UTC, VB10 commented
@MehmetKaranlik bir ss atabilir misin componetni nasil oczleim boyle lololo

2023-11-20 22:48 UTC, VB10 requested changes
bir kac ekleme

2023-11-20 22:48 UTC, VB10 commented on lib/product/widget/card/job_card_v2.dart
> +class JobCardV2 extends StatelessWidget {
v2 diye isim vermeyelim
final

2023-11-20 22:48 UTC, VB10 commented on lib/product/widget/button/general_button_v2.dart
> +class _Child extends StatelessWidget {
final

2023-11-20 22:48 UTC, VB10 commented on lib/product/widget/button/general_button_v2.dart
> +class _LoadingWidget extends StatelessWidget {
bu generic olmali sonucta her yer kulalanlbir

2023-11-22 23:28 UTC, VB10 commented
@MehmetKaranlik den ses yok bize kaldı bu iş @BerkSartik musait olunca bir ufak fixlersin bunları bro

2023-11-22 23:28 UTC, merged