feature/#125
VB-CORE/hatayi_yasat pull request #155
Opened 2023-11-26 20:18 UTC by BerkSartik

- Favorite card tasarımı yapıldı.
- Favorite card shimmer yapıldı.
- Tümünü sil ve single delete için dialog tasarımı yapıldı.

![image](https://github.com/VB-CORE/life_client/assets/48359825/084595ce-2f7f-4eef-a2db-737acc5672f0)![image](https://github.com/VB-CORE/life_client/assets/48359825/7b4a62d5-bee0-450e-8a18-58ecb7b86b14)![image](https://github.com/VB-CORE/life_client/assets/48359825/a64b9455-7944-4f84-8f74-7c31a05b5ef2)

2023-11-27 22:18 UTC, VB10 commented
https://m3.material.io/components/dialogs/specs#817cc6c7-273d-4e53-bc4a-9c776601e09c

2023-11-27 22:25 UTC, VB10 requested changes

2023-11-27 22:25 UTC, VB10 commented on lib/product/package/shimmer/author_widget_shimmer.dart
> +final class AuthorWidgetShimmer extends StatelessWidget {
buna gerek yok

2023-11-27 22:25 UTC, VB10 commented on lib/product/package/shimmer/author_widget_shimmer.dart
> +final class AuthorWidgetShimmer extends StatelessWidget {
general_shimier_avatar_container

2023-11-27 22:25 UTC, VB10 commented on lib/product/widget/appbar/page_app_bar.dart
> +            preferredSize: const Size.fromHeight(WidgetSizes.spacingXSs),
ktoolbarhegiht

2023-11-27 22:25 UTC, VB10 commented on lib/product/widget/dialog/favorite_clear_all_dialog.dart
> +final class FavoriteClearAllDialog extends StatelessWidget {
ortak
/// ne yapatigini

2023-11-27 22:25 UTC, VB10 commented on lib/product/widget/dialog/favorite_clear_all_dialog.dart
> +  static Future<void> show(BuildContext context) async {
///

2023-11-27 22:25 UTC, VB10 commented on lib/product/widget/dialog/favorite_clear_all_dialog.dart
> +final class FavoriteClearAllDialog extends StatelessWidget {
_FavoriteClearAllDialog

FavoriteClearAllDialog { static show }

2023-12-03 01:00 UTC, BerkSartik commented
![image](https://github.com/VB-CORE/life_client/assets/48359825/bb619456-e7a0-4e40-8363-aa1c483b035e)

2023-12-03 23:29 UTC, VB10 approved these changes
lgtm

2023-12-03 23:29 UTC, merged