Advertisement slider created to home view
VB-CORE/hatayi_yasat pull request #223
Opened 2024-02-24 20:27 UTC by E-MRE

# Issue #214 - Reklam Ekleme Alanı

☑️  Ana sayfa search kısmınını butona çevirip appbara koyacağız.
☑️  Ana sayfada kategorilerin üstüne banner alanı gelecek burada resimler oynayacak
☑️  Resimlere https://pub.dev/packages/carousel_slider gibi bir paketle bağlanıp oto sürekli dönecek
☑️  Bottom sheet açılacak resime basıldıktan sonra linki aç veya paylaş butonu gelecek
🔲  Push notification ile bildirim atılmış halide olacak o gelen pushlarda ana sayfa açık kalacak

[Yapılacaklar]
- Backend reklamları göndermediği için şuan mock bir liste dönüyor. Gelen listeye, modele göre düzenlemeler yapılacak.
- Push notification ile bildirim atılması konusu (Burayı konuşmakta fayda var.)
- Yükseklik 64 olarak default bir değer verildi. Dinamik veya farklı bir değer verilebilir.
- Linki aç ve paylaş butonları herhangi için aksiyonlar atanmalı.
- Lokalizasyon yapılmalı.

[Kontroller]
- Reklama tıklayınca açılan bottom sheet görünümü kontrol edilmeli (Tasarımsal isterler varsa düzeltilebilir)
- Search Field, anasayfadan appbar'a taşındı. OnPress metodu kontrol edilebilir. 

![image](https://github.com/VB-CORE/life_client/assets/34197392/54a14208-a0bf-4928-91fe-5a2962166b5d)

2024-02-24 20:58 UTC, E-MRE commented
@VB10  bazı geliştirmeler geri alındı.

![image](https://github.com/VB-CORE/life_client/assets/34197392/a0d660b5-3057-451c-9508-b94a820f8db5)

2024-02-24 23:24 UTC, VB10 requested changes
bir kac ekleme 
o slider kismiini mock bir model yapip gercek bir data ile realze edelim
ekranin %20 lik kismina denk gelsin birde

2024-02-24 23:24 UTC, VB10 commented on lib/features/home/view/widget/advertisement_slider.dart
> +    return CarouselOptions(
bunu caruseloptionsdan tureyen bir sub class yapaiblirz

2024-02-24 23:24 UTC, VB10 commented on lib/features/home/view/widget/advertisement_slider.dart
> +class _AdvertisementItem extends StatelessWidget {
f'nal

2024-02-24 23:24 UTC, VB10 commented on lib/features/home/view/widget/advertisement_slider.dart
> +          padding: const PagePadding.all(),
burada olan dialgou custom bir aler dialgo yapalim

2024-02-26 09:28 UTC, E-MRE commented
Eklemeler yapıldı

![image](https://github.com/VB-CORE/life_client/assets/34197392/4426b972-9658-44fd-9235-073bbbf9329b)

2024-02-27 18:51 UTC, E-MRE commented
conflictleri çözerken bir dünya changes oldu. Bu yüzden yeni branch oluşturdum. Bunu kapatıyorum.

2024-02-27 18:51 UTC, closed without merging