Advertisement board items updated
VB-CORE/hatayi_yasat pull request #228
Opened 2024-02-29 22:36 UTC by E-MRE

# Issue #214  - Reklam Alanı Ekleme

- Firebase'de bulunan ``` adBoard ``` tablosundaki reklamlar uygulamada gösterilecek şekilde ayarlandı.
- Reklam alanları ``` adBoardModel ``` modelinden gelen verilerle dolduruluyor.
- Reklamlar index değerine göre sıralanıp gösteriliyor.
- Reklama tıklayınca açılan bottom sheet'e owner ve description bilgileri eklendi.
- Linki Aç ve Paylaş butonlarına aksiyonlar eklendi.

NOT: main branch'te bir takım hatalar vardı. geçici olarak oralara TODO: ekledim. Sorun NotificationType.link'ten kaynaklı. Uygulamada bazı yerlerde tam karşılığı yok. 

![image](https://github.com/VB-CORE/life_client/assets/34197392/8b421c3e-b5c4-428e-8823-d06729f0072f)

![image](https://github.com/VB-CORE/life_client/assets/34197392/7ba31223-ad60-453e-aaa3-d0260eb78c9e)

2024-03-02 22:48 UTC, VB10 requested changes
bir kac ufak ekleme

2024-03-02 22:48 UTC, VB10 commented on lib/features/home/provider/advertisement_board/advertisement_board_view_model.dart
> +  Future<void> fetchAdvertisements() async {
private olmali birde class olustuurken consturctor da fetchi call atalim yada init state icinde build iicnde atmayalim kodu

2024-03-02 22:48 UTC, VB10 commented on lib/features/home/view/widget/advertisement_board_item.dart
> +    if (item.link.ext.isNotNullOrNoEmpty) {
final link = item.link
if (link.ext.null) return

2024-03-02 22:48 UTC, VB10 commented on lib/product/widget/button/open_url_general_button.dart
> +    if (!isLaunched && context.mounted) {
if () return

2024-03-03 05:08 UTC, E-MRE commented on lib/features/home/provider/advertisement_board/advertisement_board_view_model.dart
> +  Future<void> fetchAdvertisements() async {
.g oluşturduğu için private yapmadım view modeli, fonksiyonu da init state içerisinde çağırdım bu sebeple private yapmadım.

2024-03-03 05:09 UTC, E-MRE commented on lib/features/home/view/widget/advertisement_board_item.dart
> +    if (item.link.ext.isNotNullOrNoEmpty) {
ekstra bir değişkene atama yapmak istememiştim ama bu yoruma göre ayarlandı.

2024-03-03 05:10 UTC, E-MRE commented on lib/product/widget/button/open_url_general_button.dart
> +    if (!isLaunched && context.mounted) {
şartlara uyuyorsa alert göster demek ile şartlara uymuyorsa gösterme demek arasında bir fark yok aslında, yine de yoruma göre düzeltildi.

2024-03-03 09:22 UTC, kadirbekar approved these changes
eline sağlık hocam

2024-03-04 20:35 UTC, E-MRE commented
new pr opened, so this pr closed

2024-03-04 20:35 UTC, closed without merging