Special Agency Group
VB-CORE/hatayi_yasat pull request #285
Opened 2024-08-21 21:23 UTC by burakJs

<img src="https://github.com/user-attachments/assets/0c1d1611-d781-4a7c-93d1-0311711bc88b" width=250>
<img src="https://github.com/user-attachments/assets/7a8e77ea-b56f-4b2a-b4cc-16374e871a30" width=250>

2024-08-21 22:36 UTC, VB10 requested changes
eklemeler

2024-08-21 22:36 UTC, VB10 commented on lib/features/sub_feature/special_agency/provider/special_agency_view_model.dart
> +    state = state.copyWith(townNamesAndAgency: townNamesAndAgency);
bu kod cok okunaksiz olmus soyle bir iyilestirme yapaiblrsin:

Map<String, List<SpecialAgencyModel>> populateTownNamesAndAgency(
  List<SpecialAgencyModel> specialAgencyList,
  List<TownModel> townList,
) {
  // Önce town kodlarını bir Map'e dönüştürelim for hızlı erişim
  final townMap = Map.fromEntries(townList.map((town) => MapEntry(town.code, town.name)));

  return specialAgencyList.groupListsBy((agency) => townMap[agency.townCode] ?? '');
}

2024-08-21 22:36 UTC, VB10 commented on lib/features/sub_feature/special_agency/view/widget/special_agency_detail_sheet.dart
> +                  '${model.latLong.latitude},${model.latLong.longitude}';
lat long bu islem yapmadan check edleim null mu diye

2024-08-21 22:36 UTC, VB10 commented on lib/features/sub_feature/special_agency/view/widget/special_agency_detail_sheet.dart
> +                phoneNumber: phone ?? '',
mixin icine alip onTapEventi orada yapalim

2024-08-21 22:36 UTC, VB10 commented on lib/features/sub_feature/special_agency/view/widget/special_agency_detail_sheet.dart
> +                  '${model.latLong.latitude},${model.latLong.longitude}';
buda mixin icinde

2024-08-26 17:27 UTC, burakJs commented on lib/features/sub_feature/special_agency/view/widget/special_agency_detail_sheet.dart
> +                  '${model.latLong.latitude},${model.latLong.longitude}';
Hocam nullable degillermis direkt

2024-08-27 17:42 UTC, VB10 approved these changes
lgtm

2024-08-27 17:42 UTC, merged