Tab structures and FAB
VB-CORE/hatayi_yasat pull request #46
Opened 2023-09-17 14:24 UTC by BerkSartik

![image](https://github.com/VB-CORE/life_client/assets/48359825/5f238d24-af4d-4898-ba50-dc8a74f001bf) ![image](https://github.com/VB-CORE/life_client/assets/48359825/28c7d27b-0dd4-4107-9c61-3b6fb3b555f1)

2023-09-18 00:28 UTC, VB10 requested changes
yaptgımı ısın ekran gorutnusun ekleyelım

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/model/tab_model.dart
> +class _TabModel {
fınal

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/model/tab_model.dart
> +class TabModels {
final

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/tab_view.dart
> +        floatingActionButton: floatingActionButtonWidget(context),
hepsı statles wıdget olacak

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/tab_view.dart
> +  final _fabLocation = FloatingActionButtonLocation.centerDocked;
verıable atamya gerek yok

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/tab_view.dart
> +class MainTabView extends StatelessWidget {
final

2023-09-18 00:28 UTC, VB10 commented on lib/features/tab/tab_view.dart
> +  AppBar appBarWidget(BuildContext context) {
widget cıkar

2023-09-19 07:44 UTC, BerkSartik commented
> yaptgımı ısın ekran gorutnusun ekleyelım

Ekran görüntüsü eklendi. 
Conflictler çözüldü.

2023-09-21 06:12 UTC, BerkSartik commented
@VB10 
- Arka plan siyah yapıldı.
- Yazılar ortalandı.
![image](https://github.com/VB-CORE/life_client/assets/48359825/7d998189-14e5-4cda-a5e5-8e5bc8d17562)

2023-09-23 11:41 UTC, VB10 approved these changes
elıne saglık

2023-09-23 11:41 UTC, merged