Fix Navigate Bug For iOS Device
VB-CORE/hatayi_yasat pull request #56
Opened 2023-09-21 23:49 UTC by burakJs

- Fixed navigate bug for iOS device in  #55

2023-09-22 08:23 UTC, E-MRE reviewed
Good job @burakJs

2023-09-22 08:23 UTC, E-MRE commented on lib/product/utility/mixin/rediraction_mixin.dart
> +    if (Platform.isIOS) return _searchOnAppleMaps(placeAddress);
Fikir vermesi açısından yazıyorum. Burada searchOnMap fonksiyonları servis yapılabilir. Kodlama açısından daha temiz olur. Biraz metotları inceledim, kendi url'si ve default bir url var. oraya istek atılıyor exception alınırsa da default olan ile işlem yapılıyor. Ben olsan SearchOnMapService gibisinden isimle abstract açar fonksiyonu tanımlardım. Ardından google ve Apple için class lar açıp içini doldururdum. Birde abstract içinde default String url olurdu ayrıca platformSpecific url isterdim google kendi urlsini apple kendisini yazardı. Buraya geldiğinde de platforma göre ilgili sınıf çağrılır run edilirdi. Hatta factory design pattern kullanarak bu seçimi factory class'a bırakırdın. Platforma göre sana bir instance üretirdi sen sadece işi yapardın.

2023-09-22 08:36 UTC, burakJs commented on lib/product/utility/mixin/rediraction_mixin.dart
> +    if (Platform.isIOS) return _searchOnAppleMaps(placeAddress);
Dediğin gibi daha temiz görünüyor. Bu şekilde kodu temizleyip düzenleyip tekrar atarım en yakın müsait zamanımda. Teşekkür ederim değerli yorumun ve fikrin için

2023-09-23 11:47 UTC, VB10 requested changes

2023-09-23 11:47 UTC, VB10 commented on lib/product/utility/mixin/rediraction_mixin.dart
> +    if (Platform.isIOS) return _searchOnAppleMaps(placeAddress);
@E-MRE dediği önemli bir sonraki noktada issue olarak alıp bunu yapalım ama elimizde daha çok feautrler olduğu için bakıcaz

2023-09-23 11:47 UTC, VB10 commented on lib/product/utility/mixin/rediraction_mixin.dart
> +    if (Platform.isIOS) return _searchOnAppleMaps(placeAddress);
burada aynı hata google maps kısmındada var zaten olmamıs

2023-09-25 23:15 UTC, VB10 commented
buna gerek yok ben kartaldan alicam

2023-09-25 23:15 UTC, closed without merging