new project page structures added #42
VB-CORE/hatayi_yasat pull request #59
Opened 2023-09-25 09:11 UTC by BerkSartik

2023-09-25 21:54 UTC, kadirbekar approved these changes
eline sağlık

2023-09-25 21:54 UTC, kadirbekar commented on lib/features/request/project/request_project_view.dart
> +            child: SingleChildScrollView(
İhtiyaç olduğunda SingleChildScrollView widgetinin padding değerinide kullanabiliriz, Padding ile sarmalamak gibi. Hatırlatma amacıyla yazıyorum

2023-09-25 21:54 UTC, kadirbekar commented on lib/features/request/project/viewmodel/request_project_view_model.dart
> +    state =
state.isSendingRequest -> Local olarak tuttuğumuz bir değer ise default değerini false atayabiliriz, state değişikliği sırasında nullable olduğu için okunurluğu düşürebiliyor

2023-09-26 11:26 UTC, BerkSartik commented on lib/features/request/project/request_project_view.dart
> +            child: SingleChildScrollView(
FB için teşekkürler dediğiniz şekilde güncelledim kodları.

2023-09-26 11:31 UTC, BerkSartik commented on lib/features/request/project/viewmodel/request_project_view_model.dart
> +    state =
Evet local tutuyorduk. Default false olarak ayarladım. Teşekkürler

2023-09-26 20:20 UTC, VB10 requested changes

2023-09-26 20:20 UTC, VB10 commented on lib/features/request/project/model/request_project_model.dart
> +class RequestProjectModel extends Equatable {
final

2023-09-26 20:20 UTC, VB10 commented on lib/features/request/project/request_project_state.dart
> +class RequestProjectState extends Equatable {
final

2023-09-26 20:30 UTC, VB10 approved these changes

2023-09-26 20:30 UTC, merged