added notification highlight
VB-CORE/hatayi_yasat pull request #91
Opened 2023-10-11 12:32 UTC by mysCod3r

not: veriler datetime göre sıralanmıyordu. orderby createdat ayarladım.

![image](https://github.com/VB-CORE/life_client/assets/76634747/1ccd43f7-626f-4fdf-af5a-84d77a9c7d8a)

2023-10-12 07:44 UTC, E-MRE approved these changes
Eklemeler var ama opsiyonel eline sağlık

2023-10-12 07:44 UTC, E-MRE commented on lib/features/home_module/notifications/notifications_view.dart
> +      color: ColorsCustom.black,
renkleri tema yerine buradan mı veriyoruz? Eğer öyleyse sorun yok

2023-10-12 07:44 UTC, E-MRE commented on lib/features/home_module/notifications/notifications_view.dart
> +                    model.createdAt?.isAfter(lastNotificationSeen) ?? false
bu şekilde de olur ama _getColorByNotificationCreatedAt gibisinden getter veya fonksiyon ile rengi almak buradaki kod okunurluğunu arttıracaktır.

2023-10-12 07:44 UTC, E-MRE commented on lib/features/home_module/notifications/notification_mixin.dart
> +  final lastNotificationSeen = SharedCache.instance.getLastNotificationSeen();
bu da bir yöntem, late final tanımlayıp initState içinde atama yapmakta başka bir yöntem.

2023-10-12 22:22 UTC, VB10 requested changes

2023-10-12 22:22 UTC, VB10 commented on lib/product/utility/constants/string_constants.dart
> +  static const String createdAt = 'createdAt';
bunun yerı burası deıgl bu bır ındex için gerekiyor bir enum ypaıp oradan almak lazım

2023-10-13 03:46 UTC, mysCod3r commented on lib/features/home_module/notifications/notifications_view.dart
> +      color: ColorsCustom.black,
evet hocam ben yazana kadar burdan okuyorduk veli hocamın yeni pr ıyla birlikte theme den okuyacağız

2023-10-13 03:49 UTC, mysCod3r commented on lib/features/home_module/notifications/notification_mixin.dart
> +  final lastNotificationSeen = SharedCache.instance.getLastNotificationSeen();
init içerisine çektim hocam, yalnız hangi durumlarda late verip hangi durumlarda direkt eşitlemek gerekiyor bu konuda doğru yaklaşım nasıl olmalı?

2023-10-15 16:49 UTC, mysCod3r commented on lib/product/utility/constants/firebase_query_orders.dart
> +}
@VB10 hocam bunu sharede alır mıyız? size sormadan almak istemedim eğer orayada alırsak diğer lazım olabilecek query nameleri doldurup sharede alabilriim.

2023-10-15 17:38 UTC, VB10 requested changes
eklemeler

2023-10-15 17:38 UTC, VB10 commented on lib/features/home_module/notifications/notification_mixin.dart
> +    SharedCache.instance.setLastNotificationSeen();
bu kısmı bır ayrı yere alalım saveAndLastTime olsun bu businesse bu katman karışmasın

2023-10-15 17:38 UTC, VB10 commented on lib/features/home_module/notifications/notification_mixin.dart
> +        );
paginagation çalışmaya devam ediyor mu şuan

2023-10-15 17:38 UTC, VB10 commented on lib/features/home_module/notifications/notification_mixin.dart
> +  late final DateTime lastNotificationSeen;
lastNotificationSeenTime olmalı ismi

2023-10-15 17:38 UTC, VB10 commented on lib/features/home_module/notifications/notifications_view.dart
> +        : context.general.colorScheme.onInverseSurface;
benim yaptığım color mixin de light ve dark theme için bir extensin yazdım aslında ona bakar mısın

2023-10-15 17:38 UTC, VB10 commented on lib/product/feature/cache/shared_cache.dart
> +  }
null donelim set olmama durumunda ekran karar versin ne koyacagina
buradan once 
if(lastNotificationSeen.isEmpty) return null
return DateTime.tryParse(lastNotificationSeen)

2023-10-15 17:38 UTC, VB10 commented on lib/product/feature/cache/shared_cache.dart
> +      DateTime.now().toIso8601String(),
neden toIso kullandik direk normal kaydeetmedik?

2023-10-15 17:38 UTC, VB10 commented on lib/product/feature/cache/shared_cache.dart
> +  Future<void> setLastNotificationSeen() async {
etLastNotificationSeen
isimden hicbir sey anlaslmiyir

updateNotificaitonLastSeetTime

2023-10-15 17:38 UTC, VB10 commented on lib/product/utility/constants/firebase_query_orders.dart
> +}
evet alabiliriz ortak kullanima uygun ama niye descending verdin sadece anlamadim onun kararini kullanan kisi versin

en fazla withAscanding diye method yzilir ayni sekilde withAscaeding ve donulur

2023-10-15 19:14 UTC, mysCod3r commented on lib/product/feature/cache/shared_cache.dart
> +      DateTime.now().toIso8601String(),
hocam stringe çevirirken baktım toIso diye bir şey var, internette farklarına baktım, nerelerde nasıl kullanıldığına baktım. standart olarak toIso ile kullanılıyormuş. direkt toString kullanınca mesela diyelim ki benim cihazın dili eng iken uygulamaya girdim sonrasında telefon dilini tekrar tr ye çektim ve app e tekrar girdim orda bir format karmaşası olacak. toIso olduğu için böyle sorunlar olmayacak. bundan dolayı toIso olarak kullandım

2023-10-15 19:15 UTC, mysCod3r commented on lib/features/home_module/notifications/notification_mixin.dart
> +        );
evet hocam çalışıyor

2023-10-15 20:07 UTC, mysCod3r commented on lib/features/home_module/notifications/notifications_view.dart
> +        : context.general.colorScheme.onInverseSurface;
@VB10 hocam burda `ColorCommon(context).whiteAndBlackForTheme` bu şekilde kullanımdan bahsediyorsanız o renkler işimize yaramıyor bu case de. o classa renk eklemem gerekiyor ama öyle olunca da colorı yine temadan okumuş olmayacağım aslında

2023-10-15 20:55 UTC, VB10 commented on lib/features/home_module/notifications/notifications_view.dart
> +        : context.general.colorScheme.onInverseSurface;
light ve dark themeada sonucta bunların gözükmesi gereken halleri ve renkleri olmalı ikincisi burada
misal dark yaptıysan ikincisni bunun %50 opacitiylisi yparak sorunu çözersin

2023-10-15 23:20 UTC, mysCod3r commented
@VB10 
| Dark | Light |
|-|-|
![image](https://github.com/VB-CORE/life_client/assets/76634747/b5aa2ad1-a407-4819-88d5-ee1ee42dc51f)| ![image](https://github.com/VB-CORE/life_client/assets/76634747/4eab0251-5a05-43ca-b800-1906e31d868f)

2023-10-17 23:08 UTC, merged