feature/news #87
VB-CORE/hatayi_yasat pull request #96
Opened 2023-10-14 06:22 UTC by BerkSartik

![image](https://github.com/VB-CORE/life_client/assets/48359825/f98afeb5-c3b6-4b8e-8abf-7b4c08cb6bbd) ![image](https://github.com/VB-CORE/life_client/assets/48359825/f8b709d5-ee7f-48ba-801f-b44e7a9c9696)

2023-10-14 06:23 UTC, BerkSartik commented
- Pagination için uğraştım ancak ekleyemedim. Nasıl yapacağım konusunda yol gösterirseniz yapmak isterim.
- BottomTabBar'ı yeni bir tab geleceği için bıraktım. Gelen tab ile birlikte düzenleyeceğim.

2023-10-14 23:17 UTC, VB10 commented
şimdlik ayarları aşşağı alalım @BerkSartik 
pagianiton içieriide notificaon list sayfasıdna var ona bakabilr misin @BerkSartik

2023-10-14 23:19 UTC, VB10 requested changes
yoruldum okurken colorlar temadan gelecek force yok null checklere dıkkat fınal classlara

2023-10-14 23:19 UTC, VB10 commented on lib/features/news_module/news/view/news_view.dart
> +          ],
kanka ezber yapma artık gozunu sevem tek bır ıtem varsa nıye custom scroll page body vs yapıyoruz ALOOO

2023-10-14 23:19 UTC, VB10 commented on lib/features/news_module/news/view_model/news_view_model.dart
> +class NewsViewModel extends StateNotifier<NewsState> {
final

2023-10-14 23:19 UTC, VB10 commented on lib/features/news_module/news/view_model/news_view_model.dart
> +class NewsState extends Equatable {
ayri bir dosya ve final

2023-10-14 23:19 UTC, VB10 commented on lib/product/widget/card/news_card.dart
> +    return Container(
direk decoration box.

ve colorlar temadan gelecek

2023-10-14 23:19 UTC, VB10 commented on lib/product/widget/card/news_card.dart
> +      style: context.general.textTheme.titleLarge!.copyWith(
force atma colorlar temadan gelecek

2023-10-17 23:04 UTC, VB10 requested changes

2023-10-17 23:04 UTC, VB10 commented on lib/features/news_module/news_details/news_details_view.dart
> +        child: Icon(
projede base bir appbar ypatım onu kullanman lazım

2023-10-19 07:40 UTC, mysCod3r approved these changes
eline sağlık

2023-10-20 20:34 UTC, merged