Favorite button added to home view detail app bar & cache operations configured
VB-CORE/hatayi_yasat pull request #97
Opened 2023-10-14 17:14 UTC by E-MRE

Arkadaşlar şuanlık kabaca ekleme yaptım, refactor ederek son haline getireceğim. Bu esnada kod üzerine yorum satırı olarak ve commit olarakta sorularım olacak. Bu sorulara cevap verirseniz ona göre ilerleteceğim süreci.

- HomeDetailView sayfasındaki Appbar içerisine Favorilere Ekle butonu eklendi
- SharedCache ile lokale kaydedilecek şekilde ayarlandı.
- FavoritePlace modeli oluşturuldu.

2023-10-14 17:15 UTC, E-MRE commented
Sıradan bir mekan
![image](https://github.com/VB-CORE/life_client/assets/34197392/38ff7fb0-b941-4e02-abad-008a48fdd4cc)

Favori mekan
![image](https://github.com/VB-CORE/life_client/assets/34197392/4877d02f-54f6-421d-a9b5-cab3acba2609)

2023-10-14 17:16 UTC, E-MRE commented
@VB10 hocam bu favorilere ekleme veya çıkartma senaryosu mekanların listelendiği sayfada da olsun mu?

2023-10-14 17:17 UTC, VB10 commented
@E-MRE bunu mekanlarda vereceğiz aslında orada detayda fav olacak diğer kısımlar için düşünmedim bende

2023-10-14 17:20 UTC, VB10 requested changes
Model kısmında cache işlemleri değiştirilmeli ve bir mixin ile cache Logic'leri sağlanmalı

2023-10-14 17:20 UTC, VB10 commented on lib/product/feature/cache/shared_cache.dart
> +      jsonPlaces.toList(),
Bu işlem değiştirelim hive entegre edelim basitçe modelleri orada tutacağız 

o safeencode çalışmıyordu anlamadım testleri var bir bakarız ona

2023-10-14 17:21 UTC, E-MRE commented on lib/features/home_module/home_detail/home_detail_view.dart
> +  Future<void> _toggleFavorite() async {
riverpod'ta stateleri yönetmek için ayrı bir view model oluşturuyor musunuz? Örnek bir class söylerseniz benzerini burada da kullanabilirim.

2023-10-14 17:21 UTC, E-MRE commented on lib/features/home_module/home_detail/models/favorite_place_model.dart
> +final class FavoritePlaceModel extends BaseFirebaseModel<FavoritePlaceModel>
Bu modeli shared'a taşır mıyız? Bu feature neticelendirilmeden taşımak istemedim.

@VB10 hocam bu model için kritik bilgiler neler? Onları da ekleyeyim. Şuanlık sadece ismini aldım.

2023-10-14 17:21 UTC, E-MRE commented on lib/product/feature/cache/shared_cache.dart
> +  Future<bool> setFavoritePlace(FavoritePlaceModel favoritePlace) async {
Her bir cache işlemi için burayı modifiye etmek çok doğru değil sanki. Acaba diyorum bu class'tan final'ı kaldırsak ve bu arkadaşı generic bir sınıfa mı çevirsek. Diğer sınıflar bir adet key ibaresi alır, get set delete metotlarını kendine göre doldurur. @VB10 bir önerin var mıdır?

2023-10-14 17:21 UTC, E-MRE commented on lib/product/feature/cache/shared_cache.dart
> +    final jsonPlaces = places.map((place) => jsonEncode(place.toJson()));
kartal paketindeki safeJsonEncodeCompute kullanamıyorum hata veriyor.

2023-10-14 23:20 UTC, VB10 commented on lib/features/home_module/home_detail/home_detail_view.dart
> +  Future<void> _toggleFavorite() async {
içeride bir çok view model var aslında onlara  bakabilrisin lo home_View_model var

2023-10-14 23:21 UTC, VB10 commented on lib/product/feature/cache/shared_cache.dart
> +    final jsonPlaces = places.map((place) => jsonEncode(place.toJson()));
bunu anlamadım bakıcam bu cache işlemini buradnak kaldırmamız lazım

2023-10-14 23:21 UTC, VB10 commented
conflict fix need

2023-10-15 17:47 UTC, VB10 commented on lib/features/home_module/home_detail/models/favorite_place_model.dart
> +final class FavoritePlaceModel extends BaseFirebaseModel<FavoritePlaceModel>
name id adress yeterli gibi duruyor

2023-10-17 22:07 UTC, VB10 approved these changes

2023-10-17 22:07 UTC, VB10 commented on lib/product/feature/cache/hive/hive_cache_manager.dart
> +    return (count ?? 0) > 0;
box clear degılde box.remeve olmalı ve id almalı ikinci bir method etc

2023-10-17 23:05 UTC, merged